# SPDX-FileCopyrightText = © 2024 Team CharLS
# SPDX-License-Identifier = "BSD-3-Clause"

# This is a configuration file for the reuse lint tool. It allows specifing license info
# for files that cannot be extended with such info.

version = 1

[[annotations]]
path = [
    "**.pgm",
    "**.ppm",
    "**.vcxproj",
    "**.filters",
    "**/packages.config",
    "spelling.dic",
    "default.ruleset",
    "netpbm-wic-codec.sln",
    "global.json",
    "netpbm-wic-codec.sln.DotSettings"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "© 2024 Team CharLS"
SPDX-License-Identifier = "BSD-3-Clause"
