# SPDX-FileCopyrightText: © 2021 Team CharLS
# SPDX-License-Identifier: BSD-3-Clause

name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

jobs:
  build:
    name: ${{ matrix.platform }}-${{ matrix.configuration }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86
            configuration: Debug
            runner: windows-latest
          - platform: x86
            configuration: Release
            runner: windows-latest
          - platform: x64
            configuration: Debug
            runner: windows-latest
          - platform: x64
            configuration: Release
            runner: windows-latest
          - platform: ARM64
            configuration: Debug
            runner: windows-11-arm
          - platform: ARM64
            configuration: Release
            runner: windows-11-arm

    steps:
    - uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup VSTest path
      uses: darenm/Setup-VSTest@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /v:m /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} ${{env.SOLUTION_FILE_PATH}} /p:NETPBM_WIC_CODEC_ALL_WARNINGS=true

    - name: Test
      working-directory: .\build\binaries\${{matrix.platform}}\${{matrix.configuration}}\
      run: vstest.console.exe /Platform:${{matrix.platform}} test.dll
