# SPDX-FileCopyrightText: © 2021 Team CharLS
# SPDX-License-Identifier: BSD-3-Clause

name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

jobs:
  build:
    name: ${{ matrix.platform }}-${{ matrix.configuration }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86
            configuration: Debug
            runner: windows-2025-vs2026
          - platform: x86
            configuration: Release
            runner: windows-2025-vs2026
          - platform: x64
            configuration: Debug
            runner: windows-2025-vs2026
          - platform: x64
            configuration: Release
            runner: windows-2025-vs2026
          # - platform: ARM64
          #   configuration: Debug
          #   runner: windows-11-arm
          # - platform: ARM64
          #   configuration: Release
          #   runner: windows-11-arm

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - name: Setup VSTest path
      uses: darenm/Setup-VSTest@3a16d909a1f3bbc65b52f8270d475d905e7d3e44 # v1.3

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /v:m /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} ${{env.SOLUTION_FILE_PATH}} /p:NETPBM_WIC_CODEC_ALL_WARNINGS=true

    - name: Test
      working-directory: .\build\binaries\${{matrix.platform}}\${{matrix.configuration}}\
      run: vstest.console.exe /Platform:${{matrix.platform}} test.dll
